version: "3.7"

services:

   pleroma:
      build:
         context: .
      image: plerodock
      container_name: pleroma
      command: >
         python manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/code
      ports:
         - "8000:8000"
      depends_on:
         - postgres
      stdin_open: true
      tty: true     

      secrets:
         - source: pleroma_secrets
           target: /code/pleromanna/secrets.py

   postgres:
      image: postgres
      container_name: pleroma_postgres
      volumes:
         - plerodata:/var/lib/postgresql/data

secrets:
   pleroma_secrets:
      file: ~/pleroma_secrets.py

volumes:
   plerodata:
      external: true
