version: "3.7"
services:
   pleroma:
      build:
         context: .
      image: plerodock
      container_name: pleroma
      command: >
         python manage.py runserver 0.0.0.0:8000
      expose:
         - 8000
      volumes:
         - .:/code
         - pleromedia:/code/media
      depends_on:
         - postgres
      stdin_open: true
      tty: true     
      secrets:
         - source: pleroma_secrets
           target: /code/pleromanna/secrets.py
   postgres:
      image: postgres
      container_name: pleroma_postgres
      volumes:
         - plerodata:/var/lib/postgresql/data
   nginx:
      image: nginx:1.15-alpine
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      ports:
         - 80:80
         - 443:443
      volumes:
         - ./nginx:/etc/nginx/conf.d
         - ./certbot/conf:/etc/letsencrypt
         - ./certbot/www:/var/www/certbot
         - ./staticfiles:/static
         - ./mediafiles:/media
      depends_on:
         - pleroma
         - certbot
   certbot:
      image: certbot/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
      volumes:
         - ./certbot/conf:/etc/letsencrypt
         - ./certbot/www:/var/www/certbot
secrets:
   pleroma_secrets:
      file: ~/pleroma_secrets.py
volumes:
   pleromedia:
   plerodata:
      external: true
