version: "3.7"

services:

   pleroma:
      build:
         context: .
      image: plerodock
      container_name: pleroma
      volumes:
         - .:/code
         - pleromedia:/code/media
         - ~/pleroma/pleroma_secrets.py:/code/pleromanna/secrets.py
         - ~/pleroma/passwd-s3fs:/etc/passwd-s3fs
         - ~/pleroma/ssl:/code/ssl

      ports:
         - "443:8000"
      depends_on:
         - postgres
      stdin_open: true
      tty: true     
      privileged: true

   postgres:
      image: postgres
      container_name: pleroma_postgres
      volumes:
         - plerodata:/var/lib/postgresql/data

volumes:
   plerodata:
      name: plerodata
   pleromedia:
      name: pleromedia
