version: "3.1"

services:

   pleroma:
      build:
         context: .
      image: plerodock
      command: >
         sh -c "python manage.py makemigrations pleromanna &&
                python manage.py migrate &&
                gunicorn pleromanna.wsgi:application \
                 --bind 0.0.0.0:8000 --workers 3
      volumes:
         - .:/code
      ports:
         - "8000:8000"
      depends_on:
         - postgres
         - nginx
         - certbot

   postgres:
      image: postgres
      volumes:
         - plerodata:/var/lib/postgresql/data

   nginx:
      image: nginx:1.15-alpine
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - ./nginx/conf.d:/etc/nginx/conf.d
         - ./certbot/conf:/etc/letsencrypt
         - ./certbot/www:/var/www/certbot
         - ./staticfiles:/static
         - ./mediafiles:/media

   certbot:
      image: certbot/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
      volumes:
         - ./certbot/conf:/etc/letsencrypt
         - ./certbot/www:/var/www/certbot

volumes:
   plerodata:
