# Generated by Django 2.1.7 on 2019-04-05 04:35

import commonblocks.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.core.models
import wagtail.documents.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DocsPage',
            fields=[
                ('contextpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pleromanna.ContextPage')),
                ('body', wagtail.core.fields.StreamField([('doc_chooser', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('doc_list', wagtail.core.blocks.ListBlock(wagtail.documents.blocks.DocumentChooserBlock(required=False)))]))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('pleromanna.contextpage',),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('contextpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pleromanna.ContextPage')),
                ('body', wagtail.core.fields.StreamField([('event', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('start_date', wagtail.core.blocks.DateTimeBlock()), ('stop_date', wagtail.core.blocks.DateTimeBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', commonblocks.blocks.SimpleRichTextBlock(required=False))]))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('pleromanna.contextpage',),
        ),
        migrations.CreateModel(
            name='ImageryPage',
            fields=[
                ('contextpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pleromanna.ContextPage')),
                ('body', wagtail.core.fields.StreamField([('image_chooser', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('image_list', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=False)))])), ('collection_chooser', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('collection', wagtail.snippets.blocks.SnippetChooserBlock(wagtail.core.models.Collection))]))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('pleromanna.contextpage',),
        ),
        migrations.CreateModel(
            name='LessonsPage',
            fields=[
                ('contextpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pleromanna.ContextPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('pleromanna.contextpage',),
        ),
        migrations.CreateModel(
            name='PleromaHomePage',
            fields=[
                ('contextpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pleromanna.ContextPage')),
                ('heading', models.CharField(max_length=250)),
                ('notice', wagtail.core.fields.RichTextField(blank=True)),
                ('paragraph', wagtail.core.fields.RichTextField()),
                ('backdrop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('pleromanna.contextpage',),
        ),
        migrations.CreateModel(
            name='PleromaPage',
            fields=[
                ('contextpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pleromanna.ContextPage')),
                ('body', wagtail.core.fields.StreamField([('person', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('first_name', wagtail.core.blocks.CharBlock()), ('middle_name', wagtail.core.blocks.CharBlock(required=False)), ('last_name', wagtail.core.blocks.CharBlock()), ('titles', wagtail.core.blocks.CharBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('biography', commonblocks.blocks.SimpleRichTextBlock())])), ('people', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('people', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('first_name', wagtail.core.blocks.CharBlock()), ('middle_name', wagtail.core.blocks.CharBlock(required=False)), ('last_name', wagtail.core.blocks.CharBlock()), ('titles', wagtail.core.blocks.CharBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('biography', commonblocks.blocks.SimpleRichTextBlock())], required=False))), ('group_photo', wagtail.images.blocks.ImageChooserBlock()), ('group_bio', commonblocks.blocks.SimpleRichTextBlock())])), ('event', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('start_date', wagtail.core.blocks.DateTimeBlock()), ('stop_date', wagtail.core.blocks.DateTimeBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', commonblocks.blocks.SimpleRichTextBlock(required=False))])), ('article', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('paragraph', commonblocks.blocks.SimpleRichTextBlock())])), ('link', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock()), ('paragraph', commonblocks.blocks.SimpleRichTextBlock(required=False))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('pleromanna.contextpage',),
        ),
    ]
