# Generated by Django 2.2.1 on 2019-05-27 03:04

from django.db import migrations
import pleromanna.vimeoresource
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pleromanna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonspage',
            name='body',
            field=wagtail.core.fields.StreamField([('lessons', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('album_choice', wagtail.core.blocks.ChoiceBlock(choices=pleromanna.vimeoresource.Album.albums))]))]),
        ),
    ]
