# Generated by Django 2.1.5 on 2019-02-13 02:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pleromanna', '0005_auto_20190211_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonEmbedPage',
            fields=[
                ('contextpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pleromanna.ContextPage')),
                ('body', wagtail.core.fields.StreamField([('embed', wagtail.embeds.blocks.EmbedBlock())])),
            ],
            options={
                'abstract': False,
            },
            bases=('pleromanna.contextpage',),
        ),
    ]
