# Generated by Django 2.1.5 on 2019-02-14 00:34

import commonblocks.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.core.models
import wagtail.embeds.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('pleromanna', '0006_lessonembedpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonembedpage',
            name='contextpage_ptr',
        ),
        migrations.RemoveField(
            model_name='lessoncollectionpage',
            name='collection',
        ),
        migrations.AddField(
            model_name='lessoncollectionpage',
            name='body',
            field=wagtail.core.fields.StreamField([('vimeo_block', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('album', wagtail.embeds.blocks.EmbedBlock(required=False)), ('video', wagtail.embeds.blocks.EmbedBlock(required=False))])), ('collection_block', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('collection', wagtail.snippets.blocks.SnippetChooserBlock(wagtail.core.models.Collection))])), ('link_block', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock()), ('paragraph', commonblocks.blocks.SimpleRichTextBlock(required=False))]))], blank=True),
        ),
        migrations.DeleteModel(
            name='LessonEmbedPage',
        ),
    ]
