# Generated by Django 2.1.5 on 2019-02-15 01:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('pleromanna', '0007_auto_20190214_0034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonCollectionPage',
            new_name='LessonsPage',
        ),
        migrations.RemoveField(
            model_name='lessonseriespage',
            name='contextpage_ptr',
        ),
        migrations.RemoveField(
            model_name='lessonseriespage',
            name='series',
        ),
        migrations.DeleteModel(
            name='LessonSeriesPage',
        ),
    ]
