# Generated by Django 2.1.5 on 2019-02-07 02:40

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pleromanna', '0003_auto_20190205_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='pleromahomepage',
            name='notice',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
