# Generated by Django 2.1.4 on 2018-12-14 03:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pleromanna', '0005_auto_20181211_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsPage',
            fields=[
                ('contextpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pleromanna.ContextPage')),
                ('docs', wagtail.core.fields.StreamField([('docs', wagtail.core.blocks.ListBlock(wagtail.documents.blocks.DocumentChooserBlock()))])),
            ],
            options={
                'abstract': False,
            },
            bases=('pleromanna.contextpage',),
        ),
    ]
