# Generated by Django 2.1.4 on 2018-12-16 00:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pleromanna', '0006_docspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='year',
        ),
        migrations.AddField(
            model_name='contextpage',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 16, 0, 2, 36, 175776, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docspage',
            name='docs',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.CharBlock()), ('docs', wagtail.core.blocks.ListBlock(wagtail.documents.blocks.DocumentChooserBlock()))]),
        ),
    ]
