# Generated by Django 2.1.4 on 2018-12-16 05:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pleromanna', '0008_imagerypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docspage',
            name='docs',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.CharBlock()), ('docs', wagtail.core.blocks.ListBlock(wagtail.documents.blocks.DocumentChooserBlock()))], blank=True),
        ),
        migrations.AlterField(
            model_name='imagerypage',
            name='imagery',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.CharBlock()), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], blank=True),
        ),
    ]
