# Generated by Django 2.1.4 on 2018-12-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pleromanna', '0009_auto_20181216_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docspage',
            old_name='docs',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='imagerypage',
            old_name='imagery',
            new_name='body',
        ),
    ]
