# Generated by Django 2.1.4 on 2018-12-20 01:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pleromanna', '0010_auto_20181219_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerypage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.CharBlock()), ('images', wagtail.core.blocks.ListBlock(wagtail.core.blocks.URLBlock()))], blank=True),
        ),
    ]
