# Generated by Django 2.1.4 on 2018-12-22 00:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pleromanna', '0011_auto_20181220_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerypage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.CharBlock()), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], blank=True),
        ),
    ]
