# Generated by Django 2.1.4 on 2019-01-02 00:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pleromanna', '0012_auto_20181222_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerypage',
            name='body',
            field=wagtail.core.fields.StreamField([('section', wagtail.core.blocks.CharBlock()), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('collections', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='wagtailcore.collection'))], blank=True),
        ),
    ]
