# Generated by Django 2.1.4 on 2019-01-11 00:13

import commonblocks.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pleromanna', '0013_auto_20190102_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docspage',
            name='body',
            field=wagtail.core.fields.StreamField([('docs', wagtail.core.blocks.ListBlock(wagtail.documents.blocks.DocumentChooserBlock()))], blank=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=wagtail.core.fields.StreamField([('event', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock()), ('start_date', wagtail.core.blocks.DateTimeBlock()), ('stop_date', wagtail.core.blocks.DateTimeBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', commonblocks.blocks.SimpleRichTextBlock(required=False))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='imagerypage',
            name='body',
            field=wagtail.core.fields.StreamField([('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('collections', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='wagtailcore.collection'))], blank=True),
        ),
        migrations.AlterField(
            model_name='pleromapage',
            name='body',
            field=wagtail.core.fields.StreamField([('person', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock()), ('first_name', wagtail.core.blocks.CharBlock()), ('middle_name', wagtail.core.blocks.CharBlock(required=False)), ('last_name', wagtail.core.blocks.CharBlock()), ('titles', wagtail.core.blocks.CharBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('biography', commonblocks.blocks.SimpleRichTextBlock())])), ('people', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock()), ('people', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock()), ('first_name', wagtail.core.blocks.CharBlock()), ('middle_name', wagtail.core.blocks.CharBlock(required=False)), ('last_name', wagtail.core.blocks.CharBlock()), ('titles', wagtail.core.blocks.CharBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('biography', commonblocks.blocks.SimpleRichTextBlock())], required=False))), ('group_photo', wagtail.images.blocks.ImageChooserBlock()), ('group_bio', commonblocks.blocks.SimpleRichTextBlock())])), ('event', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock()), ('start_date', wagtail.core.blocks.DateTimeBlock()), ('stop_date', wagtail.core.blocks.DateTimeBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', commonblocks.blocks.SimpleRichTextBlock(required=False))])), ('article', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock()), ('subject', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('paragraph', commonblocks.blocks.SimpleRichTextBlock())]))]),
        ),
    ]
