# Generated by Django 2.1.4 on 2019-01-12 16:39

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pleromanna', '0017_auto_20190112_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docspage',
            name='body',
            field=wagtail.core.fields.StreamField([('docs', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('doc_list', wagtail.core.blocks.ListBlock(wagtail.documents.blocks.DocumentChooserBlock(required=False)))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='imagerypage',
            name='body',
            field=wagtail.core.fields.StreamField([('images', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('image_list', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=False)))])), ('collections', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('collection', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='wagtailcore.collection'))]))], blank=True),
        ),
    ]
