# Generated by Django 2.1.4 on 2019-01-13 01:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.core.models
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pleromanna', '0020_auto_20190112_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerypage',
            name='body',
            field=wagtail.core.fields.StreamField([('images', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('image_list', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=False)))])), ('collections', wagtail.core.blocks.StructBlock([('section', wagtail.core.blocks.CharBlock(required=False)), ('collection', wagtail.snippets.blocks.SnippetChooserBlock(wagtail.core.models.Collection))]))], blank=True),
        ),
    ]
