# Generated by Django 2.0.9 on 2018-10-12 02:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0004_auto_20181012_0145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='BasicPage',
        ),
    ]
