# -*- coding: utf-8 -*-
# Generated by Django 2.0.9 on 2018-10-13 06:11
from django.db import models, migrations
from wagtail.core.rich_text import RichText

def convert_to_streamfield(apps, schema_editor):
    BasicPage = apps.get_model("home", "BasicPage")
    for page in BasicPage.objects.all():
        if page.body.raw_text and not page.body:
            page.body = [('paragraph', RichText(page.body.raw_text))]
            page.save()


def convert_to_richtext(apps, schema_editor):
    BasicPage = apps.get_model("home", "BasicPage")
    for page in BasicPage.objects.all():
        if page.body.raw_text is None:
            raw_text = ''.join([
                child.value.source for child in page.body
                if child.block_type == 'paragraph'
            ])
            page.body = raw_text
            page.save()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181012_1206'),
    ]

    operations = [
        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext,
        ),
    ]
