# Generated by Django 2.0.9 on 2018-10-16 03:38

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hp_img',
        ),
        migrations.RemoveField(
            model_name='pleropage',
            name='body',
        ),
        migrations.AddField(
            model_name='pleropage',
            name='head',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pleropage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='pleropage',
            name='paragraph',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
