# Generated by Django 2.1.2 on 2018-11-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20181103_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleromahomepage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
