# Generated by Django 2.1.2 on 2018-11-08 00:33

import commonblocks.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_pleromahomepage_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleromahomepage',
            name='events',
            field=wagtail.core.fields.StreamField([('event', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateTimeBlock()), ('stop_date', wagtail.core.blocks.DateTimeBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('description', commonblocks.blocks.SimpleRichTextBlock())])))], null=True),
        ),
    ]
