# Generated by Django 2.1.2 on 2018-11-09 20:50

import commonblocks.blocks
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20181108_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='stop_date',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='events',
            field=wagtail.core.fields.StreamField([('event', wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateTimeBlock()), ('stop_date', wagtail.core.blocks.DateTimeBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('description', commonblocks.blocks.SimpleRichTextBlock())]))], blank=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='repeat_in_subnav',
            field=models.BooleanField(default=False, help_text="If checked, a link to this page will be repeated alongside it's direct children when displaying a sub-navigation for this page.", verbose_name='repeat in sub-navigation'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='repeated_item_text',
            field=models.CharField(blank=True, help_text="e.g. 'Section home' or 'Overview'. If left blank, the page title will be used.", max_length=255, verbose_name='repeated item link text'),
        ),
    ]
