# Generated by Django 2.1.2 on 2018-11-10 02:31

import commonblocks.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20181109_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='events',
            field=wagtail.core.fields.StreamField([('event', wagtail.core.blocks.StructBlock([('start_date', wagtail.core.blocks.DateTimeBlock()), ('stop_date', wagtail.core.blocks.DateTimeBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('description', commonblocks.blocks.SimpleRichTextBlock(required=False))]))], blank=True),
        ),
    ]
