# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-28 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Name of lesson', max_length=20)),
                ('description', models.CharField(help_text='Description of lesson', max_length=256)),
                ('theFile', models.FileField(upload_to='')),
            ],
        ),
    ]
