# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-29 02:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='timestamp',
            new_name='uploaded',
        ),
        migrations.AddField(
            model_name='lesson',
            name='recorded',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 2, 30, 23, 853349)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
