# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-14 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manna.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('theFile', models.FileField(storage=manna.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Document',
            new_name='Upload',
        ),
        migrations.RemoveField(
            model_name='privatedocument',
            name='user',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='upload',
            new_name='theFile',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
        migrations.DeleteModel(
            name='PrivateDocument',
        ),
    ]
