# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-31 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manna', '0002_auto_20180729_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
